// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1fhX7wQ2AUjoWw6GroWm0oSZkRutkCJk',
    appId: '1:157985293215:android:27a8395698a94ff72333aa',
    messagingSenderId: '157985293215',
    projectId: 'login-5e64a',
    storageBucket: 'login-5e64a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvIREvi2jhh2X8jPHtJcVzCBBnSmi7TFI',
    appId: '1:390242386061:ios:12e52f81654da1e06822c4',
    messagingSenderId: '390242386061',
    projectId: 'authenticate-6c233',
    storageBucket: 'authenticate-6c233.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAP6HZ5pGMhM31sacR4GkcGN3E7aXcygmc',
    appId: '1:157985293215:web:02a73377e14278df2333aa',
    messagingSenderId: '157985293215',
    projectId: 'login-5e64a',
    authDomain: 'login-5e64a.firebaseapp.com',
    storageBucket: 'login-5e64a.appspot.com',
  );

}